openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Hello, World'
  description: 'hello world'
servers:
  - url: '/hello/world/koio/'
    description: Hello world
tags:
  - name: KO Endpoints
    description: Hello World Endpoints
paths:
  /welcome:
    post:
      tags:
        - KO Endpoints
      description: Welcome.
      operationId: welcome
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcomeOutput'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    user:
      required:
        - name
      properties:
        name:
          type: string
          example: 'Bob'
    welcomeOutput:
      required:
        - result
      properties:
        result:
          type: string
          example: 'welcome'
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
